# Generated by Django 3.2.4 on 2021-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('info', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=50)),
            ],
        ),
    ]
