# Generated by Django 3.2.4 on 2021-08-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
